<?php
/**
 * Curated Font Catalog for Font Choice fields.
 *
 * Provides curated Google Web Fonts and System Web-Safe fonts.
 * Only fonts explicitly chosen by the administrator in the builder
 * will be enqueued and loaded on the storefront and builder.
 *
 * @package WooptionsFic
 */

defined('ABSPATH') || exit;

return [
	// ─── Handwriting / Script ──────────────────────────────────────────────
	[
		'id'          => 'dancing-script',
		'name'        => 'Dancing Script',
		'family'      => "'Dancing Script', cursive",
		'googleParam' => 'Dancing+Script:wght@400;700',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],
	[
		'id'          => 'pacifico',
		'name'        => 'Pacifico',
		'family'      => "'Pacifico', cursive",
		'googleParam' => 'Pacifico',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],
	[
		'id'          => 'great-vibes',
		'name'        => 'Great Vibes',
		'family'      => "'Great Vibes', cursive",
		'googleParam' => 'Great+Vibes',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],
	[
		'id'          => 'sacramento',
		'name'        => 'Sacramento',
		'family'      => "'Sacramento', cursive",
		'googleParam' => 'Sacramento',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],
	[
		'id'          => 'caveat',
		'name'        => 'Caveat',
		'family'      => "'Caveat', cursive",
		'googleParam' => 'Caveat:wght@400;700',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],
	[
		'id'          => 'alex-brush',
		'name'        => 'Alex Brush',
		'family'      => "'Alex Brush', cursive",
		'googleParam' => 'Alex+Brush',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],
	[
		'id'          => 'satisfy',
		'name'        => 'Satisfy',
		'family'      => "'Satisfy', cursive",
		'googleParam' => 'Satisfy',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],
	[
		'id'          => 'allura',
		'name'        => 'Allura',
		'family'      => "'Allura', cursive",
		'googleParam' => 'Allura',
		'category'    => 'Handwriting / Script',
		'source'      => 'google',
	],

	// ─── Serif (Elegant / Luxury / Classic) ────────────────────────────────
	[
		'id'          => 'playfair-display',
		'name'        => 'Playfair Display',
		'family'      => "'Playfair Display', serif",
		'googleParam' => 'Playfair+Display:ital,wght@0,400;0,700;1,400',
		'category'    => 'Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'merriweather',
		'name'        => 'Merriweather',
		'family'      => "'Merriweather', serif",
		'googleParam' => 'Merriweather:ital,wght@0,400;0,700;1,400',
		'category'    => 'Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'cinzel',
		'name'        => 'Cinzel',
		'family'      => "'Cinzel', serif",
		'googleParam' => 'Cinzel:wght@400;700',
		'category'    => 'Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'cormorant-garamond',
		'name'        => 'Cormorant Garamond',
		'family'      => "'Cormorant Garamond', serif",
		'googleParam' => 'Cormorant+Garamond:ital,wght@0,400;0,700;1,400',
		'category'    => 'Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'lora',
		'name'        => 'Lora',
		'family'      => "'Lora', serif",
		'googleParam' => 'Lora:ital,wght@0,400;0,700;1,400',
		'category'    => 'Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'pt-serif',
		'name'        => 'PT Serif',
		'family'      => "'PT Serif', serif",
		'googleParam' => 'PT+Serif:ital,wght@0,400;0,700;1,400',
		'category'    => 'Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'eb-garamond',
		'name'        => 'EB Garamond',
		'family'      => "'EB Garamond', serif",
		'googleParam' => 'EB+Garamond:ital,wght@0,400;0,700;1,400',
		'category'    => 'Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'bodoni-moda',
		'name'        => 'Bodoni Moda',
		'family'      => "'Bodoni Moda', serif",
		'googleParam' => 'Bodoni+Moda:ital,wght@0,400;0,700;1,400',
		'category'    => 'Serif',
		'source'      => 'google',
	],

	// ─── Sans-Serif (Modern / Clean) ───────────────────────────────────────
	[
		'id'          => 'roboto',
		'name'        => 'Roboto',
		'family'      => 'Roboto, sans-serif',
		'googleParam' => 'Roboto:wght@400;500;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'open-sans',
		'name'        => 'Open Sans',
		'family'      => "'Open Sans', sans-serif",
		'googleParam' => 'Open+Sans:wght@400;600;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'montserrat',
		'name'        => 'Montserrat',
		'family'      => "'Montserrat', sans-serif",
		'googleParam' => 'Montserrat:wght@400;600;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'lato',
		'name'        => 'Lato',
		'family'      => "'Lato', sans-serif",
		'googleParam' => 'Lato:wght@400;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'poppins',
		'name'        => 'Poppins',
		'family'      => "'Poppins', sans-serif",
		'googleParam' => 'Poppins:wght@400;600;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'inter',
		'name'        => 'Inter',
		'family'      => "'Inter', sans-serif",
		'googleParam' => 'Inter:wght@400;600;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'oswald',
		'name'        => 'Oswald',
		'family'      => "'Oswald', sans-serif",
		'googleParam' => 'Oswald:wght@400;600;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'raleway',
		'name'        => 'Raleway',
		'family'      => "'Raleway', sans-serif",
		'googleParam' => 'Raleway:wght@400;600;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],
	[
		'id'          => 'quicksand',
		'name'        => 'Quicksand',
		'family'      => "'Quicksand', sans-serif",
		'googleParam' => 'Quicksand:wght@400;600;700',
		'category'    => 'Sans-Serif',
		'source'      => 'google',
	],

	// ─── Display / Decorative ──────────────────────────────────────────────
	[
		'id'          => 'lobster',
		'name'        => 'Lobster',
		'family'      => "'Lobster', cursive",
		'googleParam' => 'Lobster',
		'category'    => 'Display',
		'source'      => 'google',
	],
	[
		'id'          => 'abril-fatface',
		'name'        => 'Abril Fatface',
		'family'      => "'Abril Fatface', cursive",
		'googleParam' => 'Abril+Fatface',
		'category'    => 'Display',
		'source'      => 'google',
	],
	[
		'id'          => 'righteous',
		'name'        => 'Righteous',
		'family'      => "'Righteous', cursive",
		'googleParam' => 'Righteous',
		'category'    => 'Display',
		'source'      => 'google',
	],
	[
		'id'          => 'comfortaa',
		'name'        => 'Comfortaa',
		'family'      => "'Comfortaa', cursive",
		'googleParam' => 'Comfortaa:wght@400;700',
		'category'    => 'Display',
		'source'      => 'google',
	],
	[
		'id'          => 'bungee',
		'name'        => 'Bungee',
		'family'      => "'Bungee', cursive",
		'googleParam' => 'Bungee',
		'category'    => 'Display',
		'source'      => 'google',
	],

	// ─── Monospace ─────────────────────────────────────────────────────────
	[
		'id'          => 'courier-prime',
		'name'        => 'Courier Prime',
		'family'      => "'Courier Prime', monospace",
		'googleParam' => 'Courier+Prime:ital,wght@0,400;0,700;1,400',
		'category'    => 'Monospace',
		'source'      => 'google',
	],
	[
		'id'          => 'inconsolata',
		'name'        => 'Inconsolata',
		'family'      => "'Inconsolata', monospace",
		'googleParam' => 'Inconsolata:wght@400;700',
		'category'    => 'Monospace',
		'source'      => 'google',
	],
	[
		'id'          => 'space-mono',
		'name'        => 'Space Mono',
		'family'      => "'Space Mono', monospace",
		'googleParam' => 'Space+Mono:ital,wght@0,400;0,700;1,400',
		'category'    => 'Monospace',
		'source'      => 'google',
	],

	// ─── System / Web-Safe ─────────────────────────────────────────────────
	[
		'id'          => 'arial',
		'name'        => 'Arial',
		'family'      => 'Arial, Helvetica, sans-serif',
		'googleParam' => null,
		'category'    => 'System / Web Safe',
		'source'      => 'system',
	],
	[
		'id'          => 'georgia',
		'name'        => 'Georgia',
		'family'      => 'Georgia, serif',
		'googleParam' => null,
		'category'    => 'System / Web Safe',
		'source'      => 'system',
	],
	[
		'id'          => 'times-new-roman',
		'name'        => 'Times New Roman',
		'family'      => "'Times New Roman', Times, serif",
		'googleParam' => null,
		'category'    => 'System / Web Safe',
		'source'      => 'system',
	],
	[
		'id'          => 'courier-new',
		'name'        => 'Courier New',
		'family'      => "'Courier New', Courier, monospace",
		'googleParam' => null,
		'category'    => 'System / Web Safe',
		'source'      => 'system',
	],
	[
		'id'          => 'impact',
		'name'        => 'Impact',
		'family'      => 'Impact, Charcoal, sans-serif',
		'googleParam' => null,
		'category'    => 'System / Web Safe',
		'source'      => 'system',
	],
	[
		'id'          => 'comic-sans',
		'name'        => 'Comic Sans MS',
		'family'      => "'Comic Sans MS', cursive, sans-serif",
		'googleParam' => null,
		'category'    => 'System / Web Safe',
		'source'      => 'system',
	],
];
