<?php
/**
 * Bundled original template catalog.
 *
 * @package WooOptionsPro
 */

defined('ABSPATH') || exit;

$t = static fn (string $text): string => did_action('init') ? __($text, 'wooptions-pro') : $text;

return [
	[
		'slug'          => 'design-your-own-pizza',
		'name'          => $t('Design-your-own Pizza'),
		'level'         => 'Beginner',
		'category'      => 'food',
		'categoryLabel' => $t('Food'),
		'fieldsCount'   => 12,
		'rulesCount'    => 4,
		'pricingModel'  => $t('Cumulative pricing'),
		'layoutModel'   => $t('Grid layout'),
		'tested'        => true,
		'description'   => $t('Let customers build their perfect pizza by choosing sauce, cheese, meats, veggies, and more with real-time pricing.'),
		'features'      => [
			$t('Image choices'),
			$t('Per-choice quantity'),
			$t('Conditional toppings'),
			$t('Cumulative pricing'),
		],
		'details'       => [
			'fields' => '12 fields',
			'rules'  => '4 rules',
			'layout' => 'Grid layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['image', 'list', 'price'],
		'fieldTypes'    => ['radio', 'segmented', 'checkbox_group', 'select', 'textarea'],
		'usage'         => 2400,
		'popularity'    => 98,
		'order'         => 130,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'gourmet-burger',
		'name'          => $t('Gourmet Burger Builder'),
		'level'         => 'Beginner',
		'category'      => 'food',
		'categoryLabel' => $t('Food'),
		'fieldsCount'   => 10,
		'rulesCount'    => 3,
		'pricingModel'  => $t('Cumulative pricing'),
		'layoutModel'   => $t('Step layout'),
		'tested'        => true,
		'description'   => $t('Let diners craft their dream burger with artisan buns, patty variations, gourmet sauces, fresh toppings, and side combos.'),
		'features'      => [
			$t('Image choices'),
			$t('Per-choice quantity'),
			$t('Cooking options'),
			$t('Cumulative pricing'),
		],
		'details'       => [
			'fields' => '10 fields',
			'rules'  => '3 rules',
			'layout' => 'Step layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['image', 'list', 'price'],
		'fieldTypes'    => ['radio', 'segmented', 'checkbox_group', 'select', 'textarea'],
		'usage'         => 2100,
		'popularity'    => 97,
		'order'         => 120,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'personalized-apparel',
		'name'          => $t('Personalized Apparel'),
		'level'         => 'Beginner',
		'category'      => 'apparel',
		'categoryLabel' => $t('Apparel'),
		'fieldsCount'   => 10,
		'rulesCount'    => 3,
		'pricingModel'  => $t('Per-item pricing'),
		'layoutModel'   => $t('Sectioned layout'),
		'tested'        => true,
		'description'   => $t('Design custom apparel with color swatches, sizes, artwork upload, and custom embroidery text.'),
		'features'      => [
			$t('Color swatches'),
			$t('Artwork upload'),
			$t('Conditional sizing'),
			$t('Per-item pricing'),
		],
		'details'       => [
			'fields' => '10 fields',
			'rules'  => '3 rules',
			'layout' => 'Sectioned layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['text', 'image', 'swatch'],
		'fieldTypes'    => ['color_swatch', 'text', 'file', 'select', 'textarea'],
		'usage'         => 1800,
		'popularity'    => 96,
		'order'         => 110,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'flower-bouquet',
		'name'          => $t('Luxury Flower Bouquet'),
		'level'         => 'Beginner',
		'category'      => 'bundles',
		'categoryLabel' => $t('Bundles'),
		'fieldsCount'   => 8,
		'rulesCount'    => 2,
		'pricingModel'  => $t('Cumulative pricing'),
		'layoutModel'   => $t('Sectioned layout'),
		'tested'        => true,
		'description'   => $t('Bespoke floral arrangements with stem count choices, signature wrapping papers, satin ribbons, custom card notes, and delivery scheduling.'),
		'features'      => [
			$t('Size tiers'),
			$t('Ribbon swatches'),
			$t('Greeting message'),
			$t('Add-on gifts'),
		],
		'details'       => [
			'fields' => '8 fields',
			'rules'  => '2 rules',
			'layout' => 'Sectioned layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['swatch', 'package', 'price'],
		'fieldTypes'    => ['radio', 'color_swatch', 'textarea', 'checkbox_group', 'date_range', 'select'],
		'usage'         => 1680,
		'popularity'    => 94,
		'order'         => 100,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'custom-mug',
		'name'          => $t('Custom Printed Mug'),
		'level'         => 'Beginner',
		'category'      => 'personalization',
		'categoryLabel' => $t('Personalization'),
		'fieldsCount'   => 8,
		'rulesCount'    => 2,
		'pricingModel'  => $t('Flat pricing'),
		'layoutModel'   => $t('Grid layout'),
		'tested'        => true,
		'description'   => $t('Personalized ceramic and enamel mugs with photo upload, custom typography, color interior choices, and gift wrap.'),
		'features'      => [
			$t('Photo upload'),
			$t('Custom typography'),
			$t('Color finishes'),
			$t('Gift packaging'),
		],
		'details'       => [
			'fields' => '8 fields',
			'rules'  => '2 rules',
			'layout' => 'Grid layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['image', 'text', 'package'],
		'fieldTypes'    => ['select', 'color_swatch', 'file', 'text', 'font', 'checkbox', 'textarea'],
		'usage'         => 1420,
		'popularity'    => 92,
		'order'         => 90,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'pet-harness',
		'name'          => $t('Custom Pet Harness'),
		'level'         => 'Beginner',
		'category'      => 'apparel',
		'categoryLabel' => $t('Apparel'),
		'fieldsCount'   => 7,
		'rulesCount'    => 2,
		'pricingModel'  => $t('Per-item pricing'),
		'layoutModel'   => $t('Grid layout'),
		'tested'        => true,
		'description'   => $t('Ergonomic custom pet harness with breed sizing, reflective colorways, engraved nameplate, phone number, and matching leash bundle.'),
		'features'      => [
			$t('Breed sizing'),
			$t('Reflective colorways'),
			$t('Custom engraving'),
			$t('Matching leash bundle'),
		],
		'details'       => [
			'fields' => '7 fields',
			'rules'  => '2 rules',
			'layout' => 'Grid layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['swatch', 'text', 'price'],
		'fieldTypes'    => ['select', 'color_swatch', 'toggle', 'text', 'checkbox_group', 'textarea'],
		'usage'         => 1250,
		'popularity'    => 90,
		'order'         => 80,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'gift-box',
		'name'          => $t('Gift Box Builder'),
		'level'         => 'Beginner',
		'category'      => 'bundles',
		'categoryLabel' => $t('Bundles'),
		'fieldsCount'   => 10,
		'rulesCount'    => 3,
		'pricingModel'  => $t('Cumulative pricing'),
		'layoutModel'   => $t('Accordion layout'),
		'tested'        => true,
		'description'   => $t('Create custom gift hampers with choice products, decorative packaging, greeting card messages, and ribbon colors.'),
		'features'      => [
			$t('Product choices'),
			$t('Custom greeting'),
			$t('Packaging options'),
			$t('Cumulative pricing'),
		],
		'details'       => [
			'fields' => '10 fields',
			'rules'  => '3 rules',
			'layout' => 'Accordion layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['package', 'image', 'price'],
		'fieldTypes'    => ['checkbox_group', 'text', 'textarea', 'radio', 'product', 'date_range'],
		'usage'         => 1100,
		'popularity'    => 89,
		'order'         => 70,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'engraving',
		'name'          => $t('Engraving'),
		'level'         => 'Beginner',
		'category'      => 'personalization',
		'categoryLabel' => $t('Personalization'),
		'fieldsCount'   => 6,
		'rulesCount'    => 2,
		'pricingModel'  => $t('Flat pricing'),
		'layoutModel'   => $t('Single column'),
		'tested'        => true,
		'description'   => $t('Personalized engraving with live font preview, line count selection, custom text placement, and velvet pouch packaging.'),
		'features'      => [
			$t('Font choices'),
			$t('Character limits'),
			$t('Custom position'),
			$t('Flat pricing'),
		],
		'details'       => [
			'fields' => '6 fields',
			'rules'  => '2 rules',
			'layout' => 'Single column',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['text', 'list'],
		'fieldTypes'    => ['text', 'toggle', 'font', 'select', 'checkbox'],
		'usage'         => 930,
		'popularity'    => 85,
		'order'         => 60,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'made-to-measure-curtains',
		'name'          => $t('Made-to-Measure Curtains'),
		'level'         => 'Advanced',
		'category'      => 'measurement',
		'categoryLabel' => $t('Measurement'),
		'fieldsCount'   => 8,
		'rulesCount'    => 2,
		'pricingModel'  => $t('Cumulative pricing'),
		'layoutModel'   => $t('Step layout'),
		'tested'        => true,
		'description'   => $t('Custom window treatments with precise width & drop measurements, fabric selection, lining options, and heading styles.'),
		'features'      => [
			$t('Formula calculations'),
			$t('Fabric choices'),
			$t('Lining upgrades'),
			$t('Cumulative pricing'),
		],
		'details'       => [
			'fields' => '8 fields',
			'rules'  => '2 rules',
			'layout' => 'Step layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['ruler', 'list', 'price'],
		'fieldTypes'    => ['number', 'select', 'checkbox_group', 'formula'],
		'usage'         => 750,
		'popularity'    => 82,
		'order'         => 50,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'custom-computer',
		'name'          => $t('Custom Computer'),
		'level'         => 'Advanced',
		'category'      => 'bundles',
		'categoryLabel' => $t('Bundles'),
		'fieldsCount'   => 8,
		'rulesCount'    => 2,
		'pricingModel'  => $t('Cumulative pricing'),
		'layoutModel'   => $t('Step layout'),
		'tested'        => true,
		'description'   => $t('PC builder with CPU, GPU, memory, storage, cooling, RGB aesthetics, and real-time compatibility rules.'),
		'features'      => [
			$t('Component choices'),
			$t('Compatibility rules'),
			$t('Dynamic pricing'),
			$t('Cumulative pricing'),
		],
		'details'       => [
			'fields' => '8 fields',
			'rules'  => '2 rules',
			'layout' => 'Step layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['chip', 'price'],
		'fieldTypes'    => ['radio', 'segmented', 'checkbox'],
		'usage'         => 1600,
		'popularity'    => 94,
		'order'         => 40,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'donation',
		'name'          => $t('Donation Amount'),
		'level'         => 'Beginner',
		'category'      => 'personalization',
		'categoryLabel' => $t('Personalization'),
		'fieldsCount'   => 5,
		'rulesCount'    => 1,
		'pricingModel'  => $t('User-defined pricing'),
		'layoutModel'   => $t('Single column'),
		'tested'        => true,
		'description'   => $t('Flexible contribution widget with preset amount buttons, custom amounts, recurring options, and dedication notes.'),
		'features'      => [
			$t('Customer-defined price'),
			$t('Preset choices'),
			$t('Honoree dedication'),
			$t('Single column'),
		],
		'details'       => [
			'fields' => '5 fields',
			'rules'  => '1 rule',
			'layout' => 'Single column',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['price', 'list'],
		'fieldTypes'    => ['segmented', 'customer_defined_price', 'toggle', 'text', 'textarea'],
		'usage'         => 540,
		'popularity'    => 72,
		'order'         => 30,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'rental-request',
		'name'          => $t('Rental Options'),
		'level'         => 'Beginner',
		'category'      => 'advanced',
		'categoryLabel' => $t('Advanced'),
		'fieldsCount'   => 7,
		'rulesCount'    => 2,
		'pricingModel'  => $t('Per-item pricing'),
		'layoutModel'   => $t('Sectioned layout'),
		'tested'        => true,
		'description'   => $t('Equipment and vehicle rental configuration with date range selection, delivery options, and damage waiver protection.'),
		'features'      => [
			$t('Date range picker'),
			$t('Insurance add-ons'),
			$t('Delivery options'),
			$t('Per-item pricing'),
		],
		'details'       => [
			'fields' => '7 fields',
			'rules'  => '2 rules',
			'layout' => 'Sectioned layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['calendar', 'list'],
		'fieldTypes'    => ['date_range', 'time', 'number', 'radio', 'checkbox', 'text'],
		'usage'         => 860,
		'popularity'    => 81,
		'order'         => 20,
		'previewUrl'    => '',
	],
	[
		'slug'          => 'team-roster',
		'name'          => $t('Team Roster'),
		'level'         => 'Beginner',
		'category'      => 'apparel',
		'categoryLabel' => $t('Apparel'),
		'fieldsCount'   => 5,
		'rulesCount'    => 1,
		'pricingModel'  => $t('Flat pricing'),
		'layoutModel'   => $t('Table layout'),
		'tested'        => true,
		'description'   => $t('Repeatable roster management for athletic teams, including player names, jersey numbers, and uniform sizes.'),
		'features'      => [
			$t('Repeatable sections'),
			$t('Row limits'),
			$t('Size choices'),
			$t('Flat pricing'),
		],
		'details'       => [
			'fields' => '5 fields',
			'rules'  => '1 rule',
			'layout' => 'Table layout',
			'tested' => 'Tested for accessibility',
		],
		'footerIcons'   => ['users', 'list'],
		'fieldTypes'    => ['text', 'select', 'repeater', 'file', 'toggle'],
		'usage'         => 430,
		'popularity'    => 68,
		'order'         => 10,
		'previewUrl'    => '',
	],
];
